services:
  mongo:
    image: mongo:3.5.10
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  boot-app:
    image: divyanshu1234567/chatback
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://divyanshubisht1624:M3W93Yr5XQ-n7i%23@cluster0.lrjfjj5.mongodb.net/
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-db:

networks:
  app-network: